### ISSUE TITLE
Non-async event loop model

### ISSUE THREAD

**Issue by tisonkun** [drmingdrmer/one_file_raft#2]
@drmingdrmer it's written -

```markdown
- [x] Non-async event loop model(main loop: `Raft::run()`).
```

But the `run` method is async -

https://github.com/drmingdrmer/one_file_raft/blob/ba379c2c831f2adaae1b70e812d76ccb32187c82/src/lib.rs#L249

**Comment by tisonkun** [comment]
It seems you're using tokio's watcher and mpsc that is driven by async runtime.

**Comment by drmingdrmer** [comment]
You are right...
I should remove that statement.
